Repository kubernetes-sigs/custom-metrics-apiserver, pull requests merged in 2022-11, with the labels that each got.

#108 Update and fix Getting Started guide
  docs/getting-started.md
  test-adapter-deploy/README.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#112 Drop pkg/dynamicmapper/fake_discovery.go
  go.mod
  go.sum
  pkg/dynamicmapper/fake_discovery.go
  pkg/dynamicmapper/mapper_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#110 Serve OpenAPI spec by default
  .gitattributes
  Makefile
  pkg/cmd/builder.go
  pkg/cmd/builder_test.go
  pkg/generated/openapi-gen.go
  pkg/generated/openapi/core/zz_generated.openapi.go
  pkg/generated/openapi/custommetrics/zz_generated.openapi.go
  pkg/generated/openapi/externalmetrics/zz_generated.openapi.go
  pkg/provider/fake/fake.go
  test-adapter/main.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#113 Bump dependencies
  go.mod
  go.sum
  pkg/apiserver/installer/apiserver_test.go
  pkg/apiserver/installer/cmhandlers.go
  pkg/apiserver/installer/emhandlers.go
  pkg/apiserver/installer/installer.go
  pkg/registry/custom_metrics/reststorage.go
  pkg/registry/external_metrics/reststorage.go
  test-adapter/main.go
  test-adapter/provider/provider.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#111 Use golangci-lint
  .golangci.yml
  Makefile
  hack/gofmt-all.sh
  pkg/apiserver/apiserver.go
  pkg/apiserver/cmapis.go
  pkg/apiserver/emapis.go
  pkg/apiserver/endpoints/handlers/get.go
  pkg/apiserver/installer/apiserver_test.go
  pkg/apiserver/installer/cmhandlers.go
  pkg/apiserver/installer/conversion.go
  pkg/apiserver/installer/emhandlers.go
  pkg/apiserver/installer/installer.go
  pkg/cmd/builder.go
  pkg/cmd/builder_test.go
  pkg/dynamicmapper/mapper.go
  pkg/provider/errors.go
  pkg/provider/fake/fake.go
  pkg/provider/interfaces.go
  pkg/provider/interfaces_test.go
  pkg/registry/custom_metrics/reststorage.go
  pkg/registry/external_metrics/reststorage.go
  test-adapter/main.go
  test-adapter/provider/provider.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#115 Add default Info.Version to OpenAPI config
  pkg/cmd/builder.go
  pkg/generated/openapi/core/zz_generated.openapi.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#116 Add olivierlemasle as reviewer
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#119 fix: add `doc.go` files to `pkg/generated/openapi/*` packages
  pkg/generated/openapi/core/doc.go
  pkg/generated/openapi/custommetrics/doc.go
  pkg/generated/openapi/externalmetrics/doc.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#120 [Backport] fix: add `doc.go` files to `pkg/generated/openapi/*` packages
  pkg/generated/openapi/core/doc.go
  pkg/generated/openapi/custommetrics/doc.go
  pkg/generated/openapi/externalmetrics/doc.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#122 Update README, mention external metrics
  README.md
  test-adapter-deploy/testing-adapter.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, needs-triage
