Repository kubernetes-sigs/custom-metrics-apiserver, pull requests merged in 2022-12, with the labels that each got.

#127 Remove duplicated import
  pkg/registry/custom_metrics/reststorage.go
  pkg/registry/external_metrics/reststorage.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, kind/cleanup, needs-triage

#124 test-adapter: refactor adding logging flags
  test-adapter-deploy/Dockerfile
  test-adapter-deploy/testing-adapter.yaml
  test-adapter/main.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, kind/cleanup, needs-triage

#123 Improve options handling
  .gitignore
  pkg/cmd/builder.go
  pkg/cmd/options/options.go
  pkg/cmd/options/options_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/cleanup, needs-triage

#129 Add license checker
  Makefile
  go.mod
  go.sum
  hack/tools.go
  pkg/dynamicmapper/mapper.go
Labels: cncf-cla: yes, size/M, lgtm, approved, needs-triage

#130 Apply Features flags (related to pprof)
  pkg/cmd/options/options.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#121 add qps/burst flag for k8s client, and provide method to hide these flags
  pkg/cmd/builder.go
Labels: cncf-cla: yes, lgtm, approved, size/S, ok-to-test

#131 Adds the option to disable APIServer's own metrics
  pkg/cmd/options/options.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage

#126 Add metric about metrics freshness
  pkg/apiserver/metrics/metrics.go
  pkg/apiserver/metrics/metrics_test.go
  pkg/registry/custom_metrics/reststorage.go
  pkg/registry/external_metrics/reststorage.go
  test-adapter/main.go
  test-adapter/provider/provider.go
Labels: cncf-cla: yes, size/L, lgtm, approved, needs-triage

#133 Bump golang.org/x/net to v0.4.0 for GO-2022-1144
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/XS, approved, triage/accepted

#136 Makefile: do not mutate manifest file
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage
