Repository kubernetes-sigs/custom-metrics-apiserver, pull requests merged in 2023-01, with the labels that each got.

#143 Bump k8s.io/client-go and k8s.io/apiserver to v0.26.0
  go.mod
  go.sum
  pkg/apiserver/endpoints/handlers/get.go
  pkg/generated/openapi/core/zz_generated.openapi.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test, triage/accepted

#144 Verify generated files in "make verify"
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-triage

#142 Add support for OpenAPI v3
  pkg/cmd/builder.go
  pkg/cmd/options/options.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, size/S, triage/accepted

#135 test-adapter: add --cert-dir to manifest
  test-adapter-deploy/testing-adapter.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, triage/accepted
