Repository kubernetes-sigs/custom-metrics-apiserver, pull requests merged in 2024-04, with the labels that each got.

#169 Docs: Add partially generated metrics reference
  docs/metrics-ref.md
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test, triage/accepted

#170 Bump K8s deps to 0.29.4
  Makefile
  go.mod
  go.sum
  pkg/cmd/builder.go
  pkg/cmd/options/options.go
  pkg/cmd/options/options_test.go
  pkg/generated/openapi/core/pkg/generated/openapi/core/zz_generated.openapi.go
  pkg/generated/openapi/core/zz_generated.openapi.go
  pkg/generated/openapi/custommetrics/pkg/generated/openapi/custommetrics/zz_generated.openapi.go
  pkg/generated/openapi/custommetrics/zz_generated.openapi.go
  pkg/generated/openapi/externalmetrics/pkg/generated/openapi/externalmetrics/zz_generated.openapi.go
  pkg/generated/openapi/externalmetrics/zz_generated.openapi.go
  test-adapter-deploy/testing-adapter.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test, needs-triage

#171 Disable priority and fairness by default
  pkg/cmd/options/options.go
  test-adapter-deploy/testing-adapter.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-triage

#173 Add dependabot
  .github/dependabot.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S, ok-to-test, needs-triage
